### ISSUE TITLE
AMI availability in quickstart template for TMOS v14

### ISSUE THREAD

**Issue by curtkersey** [F5Networks/f5-aws-cloudformation-v2#1]
## Do you already have an issue opened with F5 support?
No support case opened.

## Description
Using the 'quickstart' template, I was deploying directly from GITHUB - I chose the v14.1 PAYG 25Mbps BEST option for deploying, and I kept getting error that I was not authorized to use the AMI, ami-095cad9a666f6f3e7.  I looked at the quickstart.yaml file, and that is the mapping in the file for that AMI ID in us-east-1 for TMOS v14.1.  I found the v16 for PAYG 25Mbps BEST in the Marketplace, and I did subscribe to that.  I could not find the v14 AMI in the Marketplace, so I could not subscribe to it.  

In the end, I subscribed to the 16.1 version of the same image, ami-04598bbc0fdd5b545, and it worked.  It seems that either the AMI is incorrect for v14, or that image has been removed from AWS' Marketplace.

## Template
For bugs, enter the template with which you are experiencing issues below.

I used the stock template - deploying directly from GITHUB.  I chose the defaults for all fields, except when choosing TMOS v14 from the drop down box.

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 3

**Comment by crosbygw** [comment]
Thank you @curtkersey. 
Best 25Mbs for us-east-1 should be AMI: ami-037c5d36f26fa35bc and not AMI: ami-095cad9a666f6f3e7. I have added a task to update 14.1.4 ami map for our next release.

Here are a couple work arounds you could use until the correction is made.
* Use the parameter 'bigIpCustomImageId' with the correct ami id noted above.
* Select a different image size in us-east-1, as the rest of the ami map appears to be accurate.
* Select a different region.

**Comment by shyawnkarim** [comment]
This issue is being tracked internally with ID ESECLDTPLT-2666.

**Comment by shyawnkarim** [comment]
Closing.

This bug fix was included with [Release 1.1.0.0](https://github.com/F5Networks/f5-aws-cloudformation-v2/releases/tag/v1.1.0.0).
