### ISSUE TITLE
Deploying 3-nic got error about static route duplicates

### ISSUE THREAD

**Issue by gto481** [F5Networks/f5-aws-cloudformation-v2#17]
## Describe the bug
 
Deploy Quickstart 3-NIC PAYG got error about static route duplicates and cloud formation stack stuck in CREATE_IN_PROGRESS status
 
## Expected behavior
 
The stack should be successfully created
 
## Current behavior
 
Cloud formation stack stuck in CREATE_IN_PROGRESS status
 
## Steps to reproduce
 
1. Execute quickstart cloud formation stack with existing network
2. Input 3 subnets information for external, internal, management network
3. Choose PAYG with 3 NIC
4. Create stack
5. Run the following command to check error on BIGIP instance "**grep -ni 'error\|failure' $(sudo find /var/log -name cfn\* -or -name cloud-init\*)**"

**Example error**

{
   "code": 422,
   "body": {
      "id": "3ea40987-090d-4880-a00e-393533a58dee",
      "selfLink": "https://localhost/mgmt/shared/declarative-onboarding/task/3ea40987-090d-4880-a00e-393533a58dee",
      "code": 422,
      "status": "ERROR",
      "message": "invalid config - rolled back",
      "errors": [
         "transaction failed:01070666:3: Static route duplicates Self IP 10.0.3.0 / 255.255.255.0 implied route",
         "transaction failed:01070666:3: Static route duplicates Self IP 10.0.3.0 / 255.255.255.0 implied route"
      ],
      "result": {
         "class": "Result",
         "code": 422,
         "status": "ERROR",
         "message": "invalid config - rolled back",
         "errors": [
            "transaction failed:01070666:3: Static route duplicates Self IP 10.0.3.0 / 255.255.255.0 implied route",
            "transaction failed:01070666:3: Static route duplicates Self IP 10.0.3.0 / 255.255.255.0 implied route"
         ]
      },
      "declaration": {
         "schemaVersion": "1.0.0",
         "class": "Device",
         "label": "Quickstart 3NIC BIG-IP declaration for Declarative Onboarding with PAYG license",
         "async": true,
         "Common": {
            "class": "Tenant",
            "My_DbVariables": {
               "class": "DbVariables",
               "provision.extramb": 1000,
               "restjavad.useextramb": true,
               "ui.advisory.enabled": true,
               "ui.advisory.color": "blue",
               "ui.advisory.text": "BIG-IP Quickstart"
            },
            "My_Provisioning": {
               "class": "Provision",
               "asm": "nominal",
               "ltm": "nominal"
            },
            "My_Ntp": {
               "class": "NTP",
               "servers": [
                  "169.254.169.253"
               ],
               "timezone": "UTC"
            },
            "My_Dns": {
               "class": "DNS",
               "nameServers": [
                  "169.254.169.253"
               ]
            },
            "My_System": {
               "class": "System",
               "autoPhonehome": true,
               "hostname": "ip-10-0-2-200.ap-southeast-1.compute.internal",
               "consoleInactivityTimeout": 0,
               "cliInactivityTimeout": 0,
               "autoCheck": true,
               "tmshAuditLog": true,
               "guiAuditLog": false,
               "mcpAuditLog": "enable",
               "preserveOrigDhcpRoutes": false
            },
            "quickstart": {
               "class": "User",
               "partitionAccess": {
                  "all-partitions": {
                     "role": "admin"
                  }
               },
               "shell": "bash",
               "userType": "regular"
            },
            "default": {
               "class": "Route",
               "gw": "10.0.0.1",
               "mtu": 1500,
               "network": "default",
               "localOnly": false
            },
            "app-route": {
               "class": "Route",
               "gw": "10.0.2.1",
               "network": "10.0.3.0/24",
               "localOnly": false
            },
            "external": {
               "class": "VLAN",
               "interfaces": [
                  {
                     "name": "1.1",
                     "tagged": false
                  }
               ],
               "mtu": 1500,
               "tag": 4094,
               "autoLastHop": "default",
               "cmpHash": "default",
               "failsafeEnabled": false,
               "failsafeAction": "failover-restart-tm",
               "failsafeTimeout": 90
            },
            "external-self": {
               "class": "SelfIp",
               "address": "10.0.0.200/24",
               "allowService": "none",
               "trafficGroup": "traffic-group-local-only",
               "vlan": "external"
            },
            "internal": {
               "class": "VLAN",
               "interfaces": [
                  {
                     "name": "1.2",
                     "tagged": false
                  }
               ],
               "mtu": 1500,
               "tag": 4093,
               "autoLastHop": "default",
               "cmpHash": "default",
               "failsafeEnabled": false,
               "failsafeAction": "failover-restart-tm",
               "failsafeTimeout": 90
            },
            "internal-self": {
               "class": "SelfIp",
               "address": "10.0.3.200/24",
               "allowService": "default",
               "trafficGroup": "traffic-group-local-only",
               "vlan": "internal"
            }
         }
      }
   }
}

**Comment by shyawnkarim** [comment]
Thanks for reporting this error. I got the same behavior and have filed a bug, internal ID ESECLDTPLT-3073.

**Comment by shyawnkarim** [comment]
Closing. This issue was resolved with [Release 2.1.0.0](https://github.com/F5Networks/f5-aws-cloudformation-v2/releases/tag/v2.1.0.0).

**Comment by KrithikaChidambaram** [comment]
This was fixed in Release 2.1.0.0. 
Closing this request.
