### ISSUE TITLE
S3 bucket defaults for quickstart (or doc)

### ISSUE THREAD

**Issue by Jeremiah-007** [F5Networks/f5-aws-cloudformation-v2#20]
### Is your feature request related to a problem?
 While deploying to an existing network using the quickstart, the  "ParameterKey": "cfeS3Bucket", was defaulted in as a non-unique bucket name. 
### Describe the solution you'd like
 
It would be helpful if it were to default <accountid>-bucket, or a note in the subtext about "This should be changed to reflect a bucket that doesn't yet exist"

We did have to redeploy several times as we didn't have a good understanding that it was a new bucket.   it looks like there are 2 different s3 buckets: 1 that is used to pull data from that is owned by f5 and the new CFE that is used by us.

**Comment by shyawnkarim** [comment]
Closing. This issue was resolved with [Release 2.5.0.0](https://github.com/F5Networks/f5-aws-cloudformation-v2/releases/tag/v2.5.0.0).
