### ISSUE TITLE
CFT Template failed

### ISSUE THREAD

**Issue by themicgeinus** [F5Networks/f5-aws-cloudformation-v2#22]
BigIpInstance02 | CREATE_FAILED | Resource creation cancelled
-- | -- | -- | --
| BigIpInstance01 | CREATE_FAILED | Embedded stack arn:aws:cloudformation:us-east-1:159210315954:stack/BigIp-Failover-Existing-Network-BigIpInstance01-8XOUAVOMX0IQ/92f18b70-1215-11ed-a177-1234b2454e21 was not successfully created: The following resource(s) failed to create: [Bigip3NicInstance, S3Bucket].

**Comment by mikeshimkus** [comment]
Hi @themicgeinus, please check the troubleshooting steps and provide the logs mentioned here: https://github.com/F5Networks/f5-aws-cloudformation-v2/tree/main/examples/failover#troubleshooting-steps
thanks

**Comment by themicgeinus** [comment]
[admin@ip-10-105-3-222:NO LICENSE:Standalone] / # cat /var/log/boot.log 
Aug  2 10:49:11 localhost.localdomain notice /etc/sysconfig/sysinit/10virtual-platform.sysinit[2007]: Enabled service cloud-init-local
Aug  2 10:49:11 localhost.localdomain notice /etc/sysconfig/sysinit/10virtual-platform.sysinit[2025]: Enabled service cloud-init
Aug  2 10:49:11 localhost.localdomain notice /etc/sysconfig/sysinit/10virtual-platform.sysinit[2043]: Enabled service cloud-config
Aug  2 10:49:11 localhost.localdomain notice /etc/sysconfig/sysinit/10virtual-platform.sysinit[2061]: Enabled service cloud-final
Aug  2 10:49:12 localhost.localdomain err /etc/sysconfig/sysinit/20quickassist.sysinit[2113]: adf_ctl returned error 255
Aug  2 10:49:39 localhost.localdomain notice NET[3527]: /sbin/dhclient-script : updated /etc/resolv.conf
Aug  2 10:49:50 ip-10-105-3-222 notice vadc-init[3685]: License copying failed.
Aug  2 10:49:50 ip-10-105-3-222 notice vadc-init[3687]: vadc-init: Run all the deployment-specific startup scripts first
Aug  2 10:49:51 ip-10-105-3-222 notice aws-init[3752]: aws-init[3688]: No user specified public key found in userdata part of metadata.
Aug  2 10:49:51 ip-10-105-3-222 notice vadc-init[3789]: vadc-init: Initializing cloud-init
Aug  2 10:49:51 ip-10-105-3-222 notice cloudinit-prepare[3857]: Updated /etc/cloud/cloud.cfg with /etc/cloud/.cloud.dat.
Aug  2 10:49:51 ip-10-105-3-222 notice vadc-init[3865]: vadc-init: vadc-init - DONE
Aug  2 10:50:20 localhost.localdomain notice NET[10280]: /sbin/dhclient-script : updated /etc/resolv.conf
Aug  2 10:51:07 ip-10-105-3-222.ec2.internal notice aws-init[18457]: aws-init[3761]: Successfully posted autoscale iApp template

**Comment by shyawnkarim** [comment]
Are you still having trouble deploying?

**Comment by shyawnkarim** [comment]
Closing.

Please open another issue if you would like additional assistance.
