### ISSUE TITLE
Add AWS Global Accelerator as External DAG option 

### ISSUE THREAD

**Issue by hparr** [F5Networks/f5-aws-cloudformation-v2#24]
### Is your feature request related to a problem?
 
No
 
### Describe the solution you'd like
 
AWS Global Accelerator supports basic load balancing at the AWS Network Edge.  Some customers will use this feature since it leverages the AWS network fro the network edge in the users locality to the AWS region where applications are hosted. 
 
### Describe alternatives you've considered
 
Similar to NLB, ALB but those features cannot use the network in the same manner.
 
### Additional context
 
Create a target group per region in AWS AGA,

Deploy singe NIC BIG-IP (s) into the target group.

By default AWS AGA does not support reading AutoScale groups as targets but it can be accomplished via a lambda function 

https://aws.amazon.com/blogs/networking-and-content-delivery/updating-aws-global-accelerator-ec2-endpoints-based-on-autoscaling-group-events/

**Comment by shyawnkarim** [comment]
Thanks for submitting this RFE. It's now being tracked internally with ID ESECLDTPLT-3222. 

In order to prioritize and understand the issue better, please reach out to us at [s.karim@f5.com](s.karim@f5.com).

**Comment by shyawnkarim** [comment]
This request was reviewed by our team and we believe this falls under scope of template customization. [For help on template authoring, please see the "Getting Help" section in the documentation](https://github.com/F5Networks/f5-aws-cloudformation-v2#:~:text=the%20/examples%20folder.-,Getting%20Help,-Due%20to%20the).
