### ISSUE TITLE
s3 bucket for big-iq revocation function uses wrong/non-existing path

### ISSUE THREAD

**Issue by PiotrBratkowski** [F5Networks/f5-aws-cloudformation-v2#29]
Hello,

Looks like in autoscale-existing-network.yaml path main/ is used to get to files in version v1.2.0 layer.zip and lambda_bigiq_revoke.zip. This path does not exits. Looking here -> https://f5-aws-bigiq-revoke.s3.amazonaws.com/ it look like those versions of files (v1.2.0) only exists in develop/ folder.

 lambdaS3BucketName:
    Default: f5-aws-bigiq-revoke
    Description: REQUIRED - The name of the S3 bucket where the lambdaBigiqRevoke
      lambda function is located.
    Type: String
  lambdaS3Key:
    Default: main/
    Description: REQUIRED - The top-level key in the lambda S3 bucket where the lambda
      function is located.
    Type: String

Regards,
Piotr Bratkowski

**Comment by shyawnkarim** [comment]
Closing. Please open another issue if you still need assistance.
