### ISSUE TITLE
When will you add support for Cluster Deployment?

### ISSUE THREAD

**Issue by vkurenyshev-godaddy** [F5Networks/f5-aws-cloudformation-v2#3]
## Do you already have an issue opened with F5 support?
No

## Description
You previous repository https://github.com/F5Networks/f5-aws-cloudformation has support for cluster deployment in a single AZ or across two AZs.
Current project only state `Failover Cluster (Planned):`.

Why is that?
When are you going to add the support?

**Comment by shyawnkarim** [comment]
We hope to release our v2 cluster templates in September.

**Comment by JeffGiroux** [comment]
any updates to ha cluster template yet?

**Comment by shyawnkarim** [comment]
Our next release, with HA, is scheduled for late February.

**Comment by shyawnkarim** [comment]
Closing.

Our cluster deployments were included with [Release 2.0.0.0](https://github.com/F5Networks/f5-aws-cloudformation-v2/releases/tag/v2.0.0.0) and can be found [here](https://github.com/F5Networks/f5-aws-cloudformation-v2/tree/main/examples/failover).
