### ISSUE TITLE
Fix wording for externalPublicIpIds parameter in bigip-standalone.yaml

### ISSUE THREAD

**Issue by cmccormack** [F5Networks/f5-aws-cloudformation-v2#32]
## Documentation link
 https://github.com/F5Networks/f5-aws-cloudformation-v2/blob/a4d715d3c22fed7d779e1cd693c008636a464672/examples/modules/bigip-standalone/bigip-standalone.yaml#LL445C8-L445C8

 
## Describe the problem
Parameter description for `externalPublicIpIds` states it should be a comma-separated list of IP addresses, but for the example a list of allocation IDs is passed instead, and `AWS::EC2::EIPAssociation` `AllocationId` appears to only take an EIP Allocation ID as a parameter.  
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-eip-association.html#cfn-ec2-eipassociation-allocationid

 
## Suggested fix
 Modify the verbiage to state the list should contain allocation IDs for EIPs rather than IP addresses

**Comment by shyawnkarim** [comment]
Thanks for reporting this issue. We are now tracking it internally with ID EC-176.

**Comment by shyawnkarim** [comment]
Closing. This issue was resolved with [Release 3.1.0.0](https://github.com/F5Networks/f5-aws-cloudformation-v2/releases/tag/v3.1.0.0).
