### ISSUE TITLE
Subnet Options not Dropdowns

### ISSUE THREAD

**Issue by bradotlin** [F5Networks/f5-aws-cloudformation-v2#35]
## Describe the bug
When deploying Quickstart Existing Network from https://github.com/F5Networks/f5-aws-cloudformation-v2/tree/main/examples/quickstart, the External and Internal subnet selections are "String" fields instead of pulling subnets from your accounts subnet options using "Type: AWS::EC2::Subnet::Id" for each of those subnets parameters in the yaml.
 
## Expected behavior
 
Dropdown selections for Internal and External subnets
 
## Current behavior
 
free-form string field
 
## Possible solution
 
Change "Type" from "String" to "AWS::EC2::Subnet::Id" for  bigIpExternalSubnetId and bigIpInternalSubnetId in quickstart-existing-network.yaml

Additionally, the sshkey should be chosen from your accounts existing key pairs using Type: AWS::EC2::KeyPair::KeyName for parameter sshKey

the quickstart.yaml can also benefit from adjusting the sshkey Type: AWS::EC2::KeyPair::KeyName

**Comment by shyawnkarim** [comment]
Closing.

Disregard my last comment. An engineer on our team already looked into this and determined that this request isn't possible.
