### ISSUE TITLE
bigIpExternalServiceIps parameter in quickstart existing

### ISSUE THREAD

**Issue by bradotlin** [F5Networks/f5-aws-cloudformation-v2#36]
## Documentation link
 
While deploying https://raw.githubusercontent.com/F5Networks/f5-aws-cloudformation-v2/main/examples/quickstart/quickstart-existing-network.yaml

The template calls for bigIpExternalServiceIps. The description is 
"An array of one or more private IP addresses to apply to the external network interface as secondary private addresses."
 
## Describe the problem
 
The description states it is an array or one or more private IP addresses. However if you attempt to launch with 1 IP address, the template fails to launch. You must enter 2 IP addresses. Additionally, the IPs must be separated by a comma with no space. The comma is called out here -> https://github.com/F5Networks/f5-aws-cloudformation-v2/tree/main/examples/quickstart#deploying-this-solution, but not while deploying the template.
 
## Suggested fix
 
Edit description to state 2 IP addresses are required and they must be comma separated.

**Comment by shyawnkarim** [comment]
Thanks for reporting this issue. This issue is now being tracked internally with ID EC-219.

**Comment by shyawnkarim** [comment]
Closing.

This fix was included with [Release 3.0.0.0](https://github.com/F5Networks/f5-aws-cloudformation-v2/releases/tag/v3.0.0.0).
