### ISSUE TITLE
Documentation Fixes for Quickstart Existing

### ISSUE THREAD

**Issue by bradotlin** [F5Networks/f5-aws-cloudformation-v2#37]
## Documentation link
 
quickstart-existing-network.yaml
 
## Describe the problem
 

- In the "Network Configuration" section, "BIGIP external interface Subnet ID" is requested. IP addresses for this subnet are then asked for at the bottom of the template (BIGIP external interface Self IP). The next parameter after "BIGIP external interface Subnet ID" is "BIGIP internal interface Self IP". This is very confusing, as one would hastily think that external IPs are being asked for. Then after internal IPs are requested, then the internal subnet is requested. This is backwards. The same holds true for management IP and subnet; backwards.

- The Management IP should not be labeled "BIGIP management interface Self IP" as it is not a Self IP.
 
- VPC CIDR is requested in the Network Config section but never used.
 
- Last Parameter in the template "bigIpExternalServiceIps" asked for an array of IPs in the external subnet. The example contains an IP from the example management subnet and an example presumably from the External subnet based on the example External Self-IP. Using an IP from the Management would not work so this makes a bad example. 
 
- Furthermore, these bigIpExternalServiceIps do not appear to be assigned to the External NIC in the AWS console.  One private IP address in the external subnet is created as a secondary private IP address. So this function is broken.
  
- ## Suggested fix

- Move "BIGIP external interface Self IP" under "BIGIP external interface Subnet ID"

- Re-order the subnet/IP pairings as follows:

> 1. Mgt Subnet
> 2. Mgt IP
> 3. External Subnet
> 4. External Self-IP
> 5. Internal Subnet
> 6. Internal Self-IP

 
- Relabel "BIGIP management interface Self IP" to "BIGIP management interface IP" 
 
- Remove "VPC CIDR" parameter
 
- Fix "bigIpExternalServiceIps" as it doesn't appear to assign these IPs as secondary to the External NIC
 
- Change examples for "bigIpExternalServiceIps" to something in the same subnet.
 
- Change description of "bigIpExternalServiceIps" from "An array of one or more private IP addresses to apply to the external network interface as secondary private addresses" to "An array of two or more private IP addresses (comma separated)to apply to the external network interface as secondary private addresses to be used for Virtual Servers."

**Comment by shyawnkarim** [comment]
Thanks for bringing this to our attention. This issue is being tracked with internal ID, EC-220.

**Comment by shyawnkarim** [comment]
Closing.

This fix was included with [Release 3.0.0.0.](https://github.com/F5Networks/f5-aws-cloudformation-v2/releases/tag/v3.0.0.0)
