### ISSUE TITLE
uniqueString Key

### ISSUE THREAD

**Issue by bradotlin** [F5Networks/f5-aws-cloudformation-v2#38]
## Documentation link
 
https://github.com/F5Networks/f5-aws-cloudformation-v2/tree/main/examples/failover
 
## Describe the problem
 

- uniqueString is used to name some resources. The sample is "myUniqStr" which contains uppercase characters. This string is used to create the CFE S3 bucket (unless you specify a bucket name in "CFE S3 bucket"). If you leave the default "myUniqStr" (which you are encouraged not to) or some other value with uppercase and do NOT specify a bucket name, the template will fail stating the S3 bucket creation failed due to an uppercase character in the S3 bucket name.
- If you do specify a bucket name in "CFE S3 bucket", if you use an uppercase character the template will fail with the same error.
- The Unique String field will create a failure upon stack submission if it contains some illegal characters; such as hyphen

 
## Suggested fix
 

- change example Unique string without uppercase.
- Add instructions in the template and on GitHub readme specifying the types of characters that are allowed in Unique String and "CFE S3 bucket" (if used).

**Comment by shyawnkarim** [comment]
Thanks for reporting this issue. It's now being tracked with internal ID, EC-221.

**Comment by shyawnkarim** [comment]
Closing.

This fix was included with [Release 3.0.0.0.](https://github.com/F5Networks/f5-aws-cloudformation-v2/releases/tag/v3.0.0.0)
