### ISSUE TITLE
cfeTag parameter Value in Failover CFTs

### ISSUE THREAD

**Issue by bradotlin** [F5Networks/f5-aws-cloudformation-v2#39]
## Describe the bug
 
In the failover template, if you change the cfeTag parameter to anything but the default value provided, the CFT will fail to complete successfully
 
## Expected behavior
 
cfeTag parameter should be completely customizable since it is a String value field. If you have multiple HA pairs in the same environment, you will need to use different cfeTags
 
## Current behavior
 
If you use anything besides "bigip_high_availability_solution" for cfeTag, the template will fail on the 2 BIG-IP stacks. This is because the runtime init configs in /examples/failover/bigip-configurations/runtime-init-conf-3nic-payg-instance01.yaml and /examples/failover/bigip-configurations/runtime-init-conf-3nic-payg-instance02.yaml have a static cfeTag  

  extensionType: cf
type: inline
      value:
        schemaVersion: 1.0.0
        class: Cloud_Failover
        environment: aws
        controls:
          class: Controls
          logLevel: silly
        externalStorage:
          encryption:
            serverSide:
              enabled: true
              algorithm: AES256
          scopingTags:
           _**f5_cloud_failover_label: bigip_high_availability_solution**_

 
## Possible solution
 
runtime init should be able to us the cfeTag value from the CFT template (CFE Deployment tag value); instead of the static value
 
## Steps to reproduce
 
Launch the failover template (new network or existing network) and change the cfeTag parameter value (CFE Deployment tag value)to anything besides the default
 
## Screenshots
 
N/A
 
## Context
 
Failover CFTs fail when you customize the cfeTag

**Comment by shyawnkarim** [comment]
Thanks for submitting this issue. We are now tracking it internally with ID EC-222.

**Comment by shyawnkarim** [comment]
Closing. This issue was resolved with [Release 3.1.0.0](https://github.com/F5Networks/f5-aws-cloudformation-v2/releases/tag/v3.1.0.0).
