### ISSUE TITLE
Failed to create: [CopyZips]

### ISSUE THREAD

**Issue by elcarlodeamerica** [F5Networks/f5-aws-cloudformation-v2#5]
## Do you already have an issue opened with F5 support?
No

## Description
During the deployment of the autoscale bigiq template, we got an error when trying to create the CopyZips function

Embedded stack arn:aws:cloudformation:us-east-1:710765369567:stack/LAB5-BigIpASM-Function-1KYE93CMU5YSL/827d9f20-ea31-11eb-a17a-0a60596032c9 was not successfully created:
 The following resource(s) failed to create: [CopyZips].

Template is autoscale bigiq

## Template
Template is  autoscale.yaml   (BIGIQ)

**Comment by mikeshimkus** [comment]
Thanks for reporting.  We created internal issue #2737 to track this.

To workaround, try supplying the values below for these two template parameters:

{
    "ParameterKey": "lambdaS3BucketName",
    "ParameterValue": "f5-aws-bigiq-revoke"
},
{
    "ParameterKey": "lambdaS3Key",
    "ParameterValue": "main/"
}

**Comment by elcarlodeamerica** [comment]
Yes 
{
"ParameterKey": "lambdaS3BucketName",
"ParameterValue": "lab5lambda"
},
{
"ParameterKey": "lambdaS3Key",
"ParameterValue": "arn:aws:s3:::lab5lambda"

}

**Comment by mikeshimkus** [comment]
Are those the values you used? Should be using the values from my example above as this is where we are hosting the function code that gets copied over to a local bucket during deployment (unless you copied the zip archive to lab5lambda bucket?).

**Comment by shyawnkarim** [comment]
Closing.

The fix for this bug was included with [Release 2.0.0.0](https://github.com/F5Networks/f5-aws-cloudformation-v2/releases/tag/v2.0.0.0).
