### ISSUE TITLE
Add m5n. instance types for embedded Amazon security functionality.

### ISSUE THREAD

**Issue by Larsende** [F5Networks/f5-aws-cloudformation-v2#6]
## Do you already have an issue opened with F5 support?
No

## Description
Requesting support for Instance types due to added security functionality in AWS that supports native encryption between nitro instances:
m5n.xlarge
m5n.2xlarge

The current list has:
bigIpInstanceType:
    AllowedValues:
      - m3.2xlarge
      - m4.xlarge
      - m4.2xlarge
      - m4.4xlarge
      - m4.10xlarge
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - c3.4xlarge
      - c3.8xlarge
      - c4.4xlarge
      - c4.8xlarge
      - c5.large
      - c5.xlarge
      - c5.2xlarge
      - c5.4xlarge
      - cc2.8xlarge
      - c5n.2xlarge
      - c5n.4xlarge
    ConstraintDescription: Must be a valid EC2 instance type for BIG-IP
    Default: m5.2xlarge
    Description: Enter valid instance type.
    Type: String

**Comment by shyawnkarim** [comment]
Thanks for reporting this issue. We are now tracking your request internally with ID ESECLDTPLT-2380.

**Comment by shyawnkarim** [comment]
Closing. 

Supported instance types will continue to change with each release. If one you need is not currently in the list, please feel free to modify the template yourself and add it.
